version: 0.2


phases:
  install:
    runtime-versions:
      python: 3.6
    commands:
      - echo "Installing required libraries"
      - pip install pytest
      - pip install pynt
      - pip install poetry
      - poetry env use python3.6
      - poetry --version
      - poetry check
      - poetry install
      - echo "Installtion complete"
  pre_build:
    commands:
      - echo "Run unit test using poetry"
      - poetry run pytest tests/test__init__.py
  build:
    commands:
      - echo "Build wheel from poetry"
      - poetry build -f wheel
      - poetry check
      - echo "Run poetry check"
  post_build:
    commands:
      - echo "Run unit test using poetry"
      - poetry run pytest tests/test__init__.py
#artifacts:
  #files:
    # - We don't currently preserve any artifacts
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - We don't currently cache anything